== 9단원: 프로그램 오류 및 예외 처리

=== *요약*

* 프로그램 오류 유형
* Syntax, semantic, and logical 오류
* 컴파일 시간 및 런타임 오류
* 테스트 드라이버
* Debugging techniques
* 예외 처리
* 가장 일반적인 예외 유형
* *throws 절과 throw 문*
* • try-catch 구문을 통해 예외 잡기
* Propagation of exceptions
* • 파일에서 읽을 때의 예외(Exceptions when reading from a file)

=== 9.1 *프로그램 오류 유형*

[arabic]
. Syntax errors: 문법을 지키지 않아 발생하는 오류
. Semantic errors: 프로그램 문장의 부적절한 사용으로 인한 오류.
. Logical errors : 규격이나 사양을 따르지 않아서 발생하는 오류.

오류가 감지되는 시점에서 우리는 다음을 구별합니다. 1. Compile time
errors: syntax errors 와 static semantic errors 컴파일러에서 발생

[arabic, start=2]
. Runtime errors: dynamic semantic errors, and logical errors,
컴파일러에서 발생하지 않는 오류

=== 9.2 Syntax errors

Syntax errors 는 자바 언어 문법이 지켜지지 않았기 때문에 발생합니다.

Example 1: Missing semicolon: 세미콜론(;) 없음

[source,java]
----
int a = 5 // semicolon is missing
----

Compiler message:

[source,java]
----
Example.java:20: ';' expected
int a = 5
----

Example 2: 표현식에서 오류

[source,java]
----
x = ( 3 + 5;  // missing closing parenthesis ')'
y = 3 + * 5;   // missing argument between '+' and '*'
----

=== 9.3 Semantic errors

Semantic errors는 java 구문의 적절하지 못한 사용을 의미합니다.

_Example 1:_ Use of a non-initialized variable:

[source,java]
----
int i;
i++;    // 변수 i가 초기화되지 않았습니다.
----

_Example 2:_ Type incompatibility:

[source,java]
----
int a = "hello"; // String과 int 유형은 호환되지 않습니다.
----

_Example 3:_ Errors in expressions:

[source,java]
----
String s = "...";
int a = 5 - s;  // - 연산자는 String 유형의 인수를 지원하지 않습니다.
----

_Example 4:_ Unknown references:

[source,java]
----
Strin x;                     // 문자열이 정의되지 않았습니다.<Strin -> String>
system.out.println("hello"); // 시스템이 정의되지 않았습니다.<system -> System>
String s;
s.println();        // println is not a method of the class String
----

_Example 5:_ Array index out of range (dynamic semantic error)

[source,java]
----
int[] v = new int[10]; //배열의 길이가 10인 v 생성
v[10] = 100;           // int배열 v의 인덱스가 10번째인 int를 100으로 설정 but 인데스는 [0]부터 시작
----

배열은 10개의 요소(0~9 범위의 인덱스 포함)로 생성되었으며 존재하지 않는
인덱스 10의 요소에 액세스하려고 합니다. 이러한 유형의 오류는 컴파일
중에는 발견되지 않지만 런타임 시 예외가 발생하게 합니다.

=== 9.4 Logical errors

Logical errors는 소프트웨어 사양이 존중되지 않기 때문에
발생합니다. 프로그램이 오류 없이 컴파일되고 실행되지만 요청한 결과가
생성되지 않습니다.

Example 1: Errors in the performed computation:

[source,java]
----
public static int sum(int a, int b) {
  return a - b ;
}
// this method returns the wrong value wrt the specification that requires
// to sum two integers
----

Example 2: Non termination:

[source,java]
----
String s = br.readLine();
while (s != null) {
  System.out.println(s);
}   // this loop does not terminate<루프가 종료되지 않음>
----

=== 9.5 Errors deomtected by the compiler and runtime errors

모든 syntax errors 와 일부 semantic errors은 컴파일러에서 감지됩니다.
컴파일러는 오류 유형과 오류가 발생한 Java 소스 파일의 위치를 나타내는
메시지를 생성합니다(실제 오류는 컴파일러가 신호한 위치 이전에
발생했습니다).

_예 1:_ 0으로 나누기:

[source,java]
----
int a, b, x;
a = 10;
b = Integer.parseInt(kb.readLine());
x = a / b;  //ERROR if b = 0
----

_예 2:_ 파일이 존재하지 않습니다:

[source,java]
----
FileReader f = new FileReader("pippo.txt");
----

이 오류는 pippo.txt 파일이 하드 디스크에 없는 경우에만 발생합니다.

_예 3:_ Null 참조 역참조 :

[source,java]
----
String s, t;
s = null;
t = s.concat("a");
----

값이 null 인 참조에는 concat 메서드 를 적용할 수 없습니다 . 위
코드는 concat 메소드가 String 유형의 참조에 올바르게 적용되었기 때문에
구문상으로는 정확하지만, 값이 null 인 참조에 메소드를 적용할 수 없다는
사실로 인해 동적 의미 오류가 포함되어 있습니다 .

=== 9.6 Drivers for testing

테스트용 드라이버는 클래스나 메서드의 정확성을 테스트하는 데 사용되는
프로그램 부분입니다. 이러한 드라이버의 목적은 클래스의 공용 인터페이스에
대한 모든 메서드를 호출하고 해당 메서드가 사양을 준수하는지 확인하는
것입니다.

완전한 테스트를 수행하려면 몇 가지 지침을 따라야 합니다.

* 각 기능(각 방법)을 확인합니다.
* 특정 순서에 따라 테스트를 수행합니다(방법 적용 순서가 중요한 경우가
많습니다).
* 각 명령문이 적어도 한 번은 실행되는지 확인합니다. 예를 들어 조건문이
있는 경우 부울 조건이 각각 참과 거짓이 되는 방식으로 입력의 다양한
구성에 대한 테스트를 수행해야 합니다.
* 특별한 경우(예: 파일에서 읽는 메서드에 대한 입력으로 빈 파일)를
감지하고 테스트합니다.

=== 9.7 Techniques for detecting errors (debugging)

테스트 단계에서 논리적 오류가 있음을 알리거나 런타임 오류의 원인을
감지할 수 없는 경우 프로그램을 *디버깅 해야 합니다.*

프로그램 디버깅에 도움이 되는 정보를 얻을 수 있는 방법에는 두 가지가
있습니다.

[arabic]
. 코드에 출력 문을 삽입하여;
. *디버거를* 통해 프로그램을 실행함으로써 .

=== 9.8 Debugging by inserting output statements

이 디버깅 기술은 오류를 일으키는 잘못된 값을 포함할 수 있는 변수의
내용을 인쇄하는 소스 코드 문의 적절한 위치에 삽입하는 것을 기반으로
합니다.

Example:

[source,java]
----
int a, b, x;
a = 5;
b = Integer.parseInt(kb.readLine()); // reading of b
...         // statements that do not change b
x = a/b;
----

_이 프로그램 명령문을 디버깅하기_ 위해 b 값을 화면에 인쇄하여
변수 b 값이 0 일 때 오류가 발생하는지 확인할 수 있습니다.

[source,java]
----
int a, b, x;
a = 5;
b = Integer.parseInt(kb.readLine()); // reading of b
...         // statements that do not change b
System.out.println("b = " + b);
x = a/b;
----

오류의 원인이 식별되고 수정되면 디버깅 세션을 닫기 전에 인쇄 문을 제거할
수 있습니다.

_참고:_ 기본 데이터 유형의 단순한 변수가 아닌 객체의 내용을 탐색해야
하는 경우 객체의 내용에 대한 정보를 제공하는 toString 메소드를 사용할 수
있습니다 . 디버깅하는 동안 개체 상태 읽기를 단순화하기
위해 toString을 재정의할 수도 있습니다 .

=== 9.9 Execution of the program by means of a debugger

디버거를 사용하면 다음을 수행할 수 있습니다.

* 한 번에 하나씩 프로그램의 명령문을 실행하고,
* 실행이 사용자가 Break Point( *중단점*
+
이라고 함 )에 도달할 때까지 프로그램을 실행합니다.
* 실행 중 언제든지 변수와 개체의 내용을 검사합니다.

디버거는 프로그램 오류의 원인을 탐지하는 데 매우 유용한 도구입니다.

[source,java]
----
int a, b, x;
a = 5;
b = Integer.parseInt(kb.readLine()); // reading of b
...         // statements that do not change b
x = a/b;
----

디버거를 통해 오류를 생성하는 명령문을 실행하기 전에 변수 b 의 값을
확인할 수 있습니다.

[source,java]
----
String s, t;
s = null;
...
t = s.concat("a");
----

t 에 대한 할당문은 NullPointerException 유형의 예외를
생성합니다 . 이러한 오류는 대입문이 실행될 때 s 값이 null 이라는 사실에
따라 달라집니다 . 이 오류를 확인하려면 오류를 생성하는 명령문을 실행하기
전에 디버거를 사용하고 변수 s 의 값을 관찰하면 됩니다 .

=== 9.10 Handling errors during the execution of programs

프로그램을 실행하는 동안 프로그램이 예기치 않게 비정상적으로 종료되는
다양한 상황이 발생할 수 있습니다.

_예:_ 다음 프로그램을 고려해보세요.

[source,java]
----
public class TestException {
  public static void main (String[] args) {
    int falseNumber = Integer.parseInt("OK");
    System.out.println("this println statement is not executed");
  }
}
----

다음 메시지가 화면에 인쇄됩니다.

....
Exception in thread "main" java.lang.NumberFormatException: For input string: "OK"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
  at java.lang.Integer.parseInt(Integer.java:468)
  at java.lang.Integer.parseInt(Integer.java:518)
  at TestException.main(TestException.java:3)
....

따라서 "`this println statement is not executed`"라는문자열이 인쇄되지
않습니다.

*Java에서는 런타임 시 발생하는 오류를 예외* 로 표현합니다 . Java는
프로그램 실행 중에 발생할 수 있는 사전 정의된 예외 세트를 제공합니다.

프로그램이 예기치 않게 종료되는 것을 방지하기 위해 Java에서는 적절한
구성을 통해 예외를 처리할 수 있습니다.

=== 9.11 The hierarchy of exceptions

예외 및 오류는 Java 클래스를 통해 표시되며 계층 구조로 구성됩니다.

Throwable 클래스 는 모든 유형의 오류와 모든 예외의
슈퍼클래스입니다. 오류는 프로그래머가 제어할 수 없는
이벤트(예: OutOfMemoryError )를 나타내는 반면, 예외는 프로그램 실행 중에
처리될 수 있습니다.

image::https://github.com/NHN-academy-Avocado/Avocado/assets/115917642/1598135d-b202-46fa-8055-15644fa6dd5d[Untitled]


_참고:_ 이 그림에서 점선은 간접 상속 관계를 나타냅니다.

=== 9.12 How to handle exceptions

예외 처리에는 두 가지 가능성이 있습니다.

* 생성된 예외 처리
* 프로그램의 다른 지점에서 예외 처리

_대신 예외가 처리되지 않으면 프로그램이 종료되고 메시지가 인쇄됩니다._

예를 들어, 0으로 나누기를 시도하면 다음과 같은 결과를 얻습니다.

....
Exception in thread "main" java.lang.ArithmeticException: / by zero
  at DivByZero.main(DivByZero.java:7)
....

=== 9.13 The most common types of exceptions

[arabic]
. NullPointerException: 메서드를 호출하는 데 사용된 참조의 값이 null
이거나 null 참조 를 통해 인스턴스 변수에 액세스하려고 할 때
생성됩니다 . 일부 메서드는 null 인 매개 변수가 전달될 때 명시적으로
이러한 유형의 예외를 발생시킵니다 .
. ArrayIndexOutOfBoundsException: 0보다 작거나 배열 길이에서 1을 뺀
값보다 큰 인덱스를 사용하여 배열 요소에 액세스할 때 생성됩니다.
. IOException: 오류 상황이 발생했을 때 입출력 장치에 접근하는 메소드에
의해 생성됩니다.
. FileNotFoundException: 존재하지 않는 파일을 열려고 할 때 생성됩니다.
. NumberFormatException: 문자열을 숫자로 변환하는 메서드에 의해
생성됩니다. 예를 들어, Integer.parseInt는 매개변수로 전달된 문자열에
숫자가 포함되지 않은 경우 이 유형의 예외를 생성합니다.

=== 9.14 The throws clause

모든 Java 메소드는 throws 절을 사용하여 호출하는 메소드에 의해 생성된
예외를 처리할 수 있습니다.

throws 절이 메서드 정의 의 헤더에 추가됩니다. 

For example:

[source,java]
----
public static void main(String[] args) throws IOException {
  ...
}
----

=== 9.15 Checked exceptions and runtime exceptions

_확인된_ 예외는 해당 예외 가 발생할 수 있는 모든 메서드의 throws 절 에
언급되어야 합니다 . 그런 다음 이러한 예외는 예외가 발생한 메서드를
호출하는 메서드로 전파됩니다.

예를 들어, 메서드 A가 MyException 유형의 예외를 발생시키도록 선언하는
경우 A 를 호출하는 모든 메서드는 이러한 예외를 발생시킨다고 자체적으로
선언하거나 예외를 포착해야 합니다(나중에 참조). 따라서 다음 코드 조각은
잘못된 것입니다. 왜냐하면 메서드 B 가 MyException 유형의 예외를
발생시키도록 선언하지 않고 A 에서 생성할 수 있는 예외를 포착하지 않기
때문입니다 .

[source,java]
----
public static void A() throws MyException {
  ...
}

public static void B() {
  A();
}
----

_확인되지 않은 예외는_ RuntimeException 유형(하위 클래스)의
객체입니다 . 프로그램 실행 중에 JVM(Java Virtual Machine)에서 발생하는
예외를 나타냅니다. 이 수업에는 다음이 포함됩니다:

* 산술 예외(예: 0으로 나누기)
* 참조 예외(예: null
+
참조를 통해 객체에 액세스하려고 시도 )
* 배열을 인덱싱할 때 예외(예: 인덱스가 너무 작거나 큰 배열 요소에
액세스하려고 시도하는 경우)

=== 9.16 Definition of new exceptions

새로운 예외는 Exception 클래스 나 그 하위 클래스 중 하나에서 시작하여
정의할 수 있습니다.

[source,java]
----
public class MyException extends Exception {
  public MyException (String message) {
    super(message);
  }
}
----

MyException 클래스는 시각화할 특정 메시지를 지정합니다. 예외 의
생성자는 예외가 발생할 때 인쇄되는 문자열을 매개변수로 사용합니다 .

Exception 대신 RuntimeException 의 하위 클래스로 예외 클래스를 정의하는
것도 가능합니다 . _이러한 방식으로 이러한 예외는 unchecked_ 유형이므로
명시적으로 처리할 필요가 없습니다 .

=== 9.17 The throw statement

예외를 발생시키려면 throw 문을 사용합니다.

Syntax:

[source,java]
----
throw exceptionObject ;
----

exception 객체는 Exception 클래스 (또는 그 하위 클래스 중 하나)

Semantics:

throw 문의 매개 변수로 나타나는 객체가 나타내는 유형의 예외를
발생시킵니다 .

Example:

[source,java]
----
throw new MyException("message for MyException");
----

이 명령문은 생성자에 대한 매개변수로 나타나는 메시지를 화면에
인쇄하는 MyException 유형의 예외를 발생시킵니다 .

=== 9.18 Example

[source,java]
----
import java.io.*;

public class UseMyException {
  public static void main(String[] args) throws MyException, IOException {
    int min = 10, max = 30;
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    System.out.println("Input a number between " + min +
                       " and " + max + " included");
    int value = Integer.parseInt(br.readLine());
    if (value < min || value > max)
       throw new MyException("The value is not in the allowed interval");
    System.out.println("The value is in the allowed interval");
  }
}
----

다음은 프로그램 실행의 예입니다.

....
Input a number between 10 and 30 included
9
....

....
Exception in thread "main" MyException: The value is not in the allowed interval
  at UseMyException.main(UseMyException.java:11)
....

_참고:_ MyException 클래스를 Exception 대신 RuntimeException 의 하위
클래스로 정의했다면 기본 메서드 정의의 throws 절
에 MyException을 표시하지 않아도 되었을 것입니다 .

=== 9.19 How to catch an exception

hrow 문은 throw 문을 실행하는 메서드에서 시작하여 기본
메서드까지 호출 메서드까지 진행되는 메서드 종료 체인을 시작합니다 .

예외가 발생하면 _프로그램_ 종료로 이어지는 일련의 예외가 중단됩니다.

예외를 포착하려면 try-catch-finally 구조를 사용할 수 있습니다.

[source,java]
----
try {
  try-block
}
catch(ExceptionClass1 e) {
  catch-block
}
catch(ExceptionClass2 e) {
  catch-block
}
...
finally {
  finally-block
}
----

* _try-block_ : 다음 catch 절의 제어 하에 실행될 일련의 명령문
* _catch-block : try-block_ 의 명령문이 해당 catch 절 에 지정된 유형의
예외를 생성하는경우 실행될 명령문 시퀀스
* _finally-block : 항상 실행되는 일련의 명령문입니다( try-block이_ 예외
없이 실행되는 경우예외를 잡기 위해 _catch-block이_ 실행되는 경우
+
Semantics:
+
코드 조각에서 발생할 수 있는 하나 이상의 예외를 포착합니다. 이러한
명령문 중 하나가 예외를 생성하는 경우 _try-block_ 의 명령문 실행이
중단됩니다. 이런 일이 발생하면 catch 절은 작성된 순서대로 평가되고
생성된 예외가 지정된 클래스에 속하는 첫 번째 절에 해당하는 _catch
블록이_ 실행됩니다. _마지막으로 finally 블록_ 의 명령문이 실행됩니다.
+
Example:
+
[source,java]
----
try {
   System.out.println(Integer.parseInt(br.readLine());
}
catch(IOException e1) {
   System.out.println("An IO error occurred.");
}
catch(NumberFormatException e2) {
   System.out.println("The string read does not contain an integer.");
}
finally {
   System.out.println("Block executed.");
}
----
+
이 코드 조각은 입력 채널에서 읽은 문자열을 정수로 변환하고 정수를
인쇄하려고 시도합니다. IO 오류가 발생하거나 읽은 문자열에 일련의 숫자가
포함되어 있지 않으면 해당 오류 메시지가 비디오에 인쇄됩니다. 어떤
경우든 finally 절 에 해당하는 "`Block 실행됨`" 문자열에
대한 println 문이 실행됩니다.
+
### 9.21 Example of exception handling
+
data.txt 파일에 저장된 음수가 아닌 정수 값 시퀀스의 최대값을 인쇄하는
Java 프로그램을 작성하세요 .
+
먼저 예외를 고려하지 않고 문제에 집중합니다.
+
[source,java]
----
import java.io.*;

public class MaximumWithoutExceptions {
  public static void main (String args[]) throws IOException {
    BufferedReader br = new BufferedReader(new FileReader("data.txt"));
            // could generate FileNotFoundException (checked)
    int max = -1;

    String line = br.readLine();
            // could generate IOException (checked)
    while (line != null) {
      int n = Integer.parseInt(line);
          // could generate NumberFormatException (unchecked)
      if (n > max) max = n;
      line = br.readLine();
          // could generate IOException (checked)
    }
    System.out.println("Maximum = " + max);
  }
}
----
+
이제 예외를 고려해 보겠습니다.
+
[source,java]
----
import java.io.*;

public class MaximumWithExceptions {
  public static void main (String args[]) {
    try {
      BufferedReader br = new BufferedReader(new FileReader("data.txt"));
                // could generate FileNotFoundException (checked)
      int max = -1;

      String line = br.readLine();
                // could generate IOException (checked)
      while (line != null) {
        int n = Integer.parseInt(line);
                // could generate NumberFormatException (unchecked)
        if (n > max) max = n;
        line = br.readLine();
                // could generate IOException (checked)
      }
      if (max == -1)
         throw new Exception("File empty or all numbers < 0");
      else
         System.out.println("Maximum = " + max);
      }
    catch (FileNotFoundException e) {
       System.out.println("The file does not exist.");
    }
    catch (IOException e) {
       System.out.println("The file cannot be read.");
    }
    catch (NumberFormatException e) {
       System.out.println("The file contains non numeric data.");
    }
    catch (Exception e) {
       System.out.println(e.getMessage());
    }
  }
}
----
+
파일에 정수 값으로 변환할 수 없는 영숫자 데이터가 포함되어 있으면 첫
번째 프로그램에서 다음 오류 메시지가 생성됩니다.
+
....
Exception in thread "main" java.lang.NumberFormatException: For input string: "pippo"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:48)
  at java.lang.Integer.parseInt(Integer.java:468)
  at java.lang.Integer.parseInt(Integer.java:518)
  at MaximumWithoutExceptions.main(MaximumWithoutExceptions.java:12)
....
+
대신 두 번째 프로그램은 예외를 처리하고 다음을 인쇄합니다.
+
....
The file contains non numeric data.
....
+
### 9.22 Propagation of exceptions
+
예외가 발생한 곳에서 예외가 포착되지 않고 처리되지 않으면 예외가 발생한
메서드를 호출한 메서드로 제어가 전달됩니다. 예외가 포착되거나
컨트롤이 프로그램을 종료하고 오류 메시지를 생성하는 기본 메서드로 전달될
때까지 전파가 계속됩니다.
+
메소드 종료 체인을 시작하는 것은 throw 문 입니다 .
+
For example:
+
[source,java]
----
import java.io.*;

public class ExceptionPropagation1 {

  public static void main(String[] args) throws Exception {
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    System.out.println("Insert a number:");
    int c = Integer.parseInt(br.readLine());
    first(c);
  }

  private static void first(int a) throws Exception {
    second(a);
  }

  private static void second(int b) throws Exception {
    Exception propagate = new Exception("The value is too small.");
    if (b < 10)
      throw propagate;
    System.out.println("OK");
  }
}
----
+
프로그램이 10보다 작은 값(예: 5)을 읽으면 예외가 발생하고 다음 메시지가
인쇄됩니다.
+
....
Insert a number:
5
Exception in thread "main" java.lang.Exception: The value is too small.
  at ExceptionPropagation1.second(ExceptionPropagation1.java:17)
  at ExceptionPropagation1.first(ExceptionPropagation1.java:13)
  at ExceptionPropagation1.main(ExceptionPropagation1.java:9)
....
+
두 번째 메소드에 의해 시작된 종료 체인이 기본 메소드 로
전파되도록 하려면 종료 체인의 일부인 모든 메소드의 헤더에 관련 예외
목록이 있는 throws 절이 있어야 합니다 . 이 경우에는 Exception 만
있습니다 .
+
### 9.23 Interrupting the propagation of exceptions
+
다음 예제에서는 예외를 생성하는 메서드에서 예외가 처리되지 않고 예외를
생성하는 메서드를 호출하는 메서드에서 처리됩니다. 그러면 예외가 더 이상
위쪽으로 전파되지 않습니다. 따라서 첫 번째 및 주요 메소드는 예외를
발생시키도록 throws 절 에서 선언할 필요가 없습니다
+
[source,java]
----
import java.io.*;

public class ExceptionPropagation2 {

  public static void main(String[] args) throws IOException {
    BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
    System.out.println("Insert a number:");
    int c = Integer.parseInt(br.readLine());
    first(c);
  }

  private static void first(int a) {
    try {
      second(a);
    }
    catch (Exception e) {
      System.out.println("Exception handled in the first method.");
      System.out.println(e.getMessage());
    }
  }

  private static void second(int b) throws Exception {
    Exception propagate = new Exception("The value is too small.");
    if (b < 10)
      throw propagate;
    System.out.println("OK");
  }
}
----
+
이전과 동일한 입력에 대해 이 프로그램을 실행한 결과는 다음과 같습니다.
+
....
Insert a number:
5
Exception handled in the first method.
The value is too small.
....
+
### 9.24 Example of exception handling when reading from a file
+
파일에서 정수 값을 읽고 이를 표준 출력으로
인쇄하는 printIntegers 메소드를 작성하십시오 . 정수 값을 포함하지 않는
파일 행(예: 알파벳 문자 포함)의 경우 프로그램은 “***“ 문자열을 인쇄 하고
파일에서 계속 읽어야 합니다.
+
[source,java]
----
public static void printIntegers(String filename) {
  try {  // cattura exceptions di IO
    FileReader f = new FileReader(filename);
    BufferedReader in = new BufferedReader(f);
    String line = in.readLine();
    while (line != null) {
      try { // capture NumberFormaException
        int n = Integer.parseInt(line);
        System.out.println(n);
      }
      catch(NumberFormatException e) {
        System.out.println("***");
      }
      line = in.readLine();
   }
  }
  catch (IOException e) {
    System.out.println(e.getMessage());
  }
}
----
+
*Exercises*
+
*연습 09.1* 다음 프로그램이 _(i)_  컴파일 오류, _(ii)_  런타임 오류를
생성하는지 확인하세요. 프로그램이 오류를 생성하지 않으면 무엇을 인쇄할지
말하십시오. 프로그램에서 오류가 발생하면 오류를 수정하고 수정 후 무엇을
인쇄할지 말하세요. 답변에 동기를 부여하십시오.
+
[source,java]
----
public class Exercise1 {
  public static void main(String[] args) {
    for (int i = 0, j = 0; i < 10, j < 10; i++, j++) {
      System.out.println(i + " + " + j + " = " + (i+j));
    }
    System.out.println("I've printed out the sums of i and j up to "
                       + i + "," + j);
  }
}
----
+
*연습 09.2* 다음 프로그램이 _(i)_  컴파일 오류, _(ii)_  런타임 오류를
생성하는지 확인하세요. 프로그램이 오류를 생성하지 않으면 무엇을 인쇄할지
말하십시오. 프로그램에서 오류가 발생하면 오류를 수정하고 수정 후 무엇을
인쇄할지 말하세요. 답변에 동기를 부여하십시오.
+
[source,java]
----
public class Exercise2 {

  private int x = 101;

  private void f(int x) {
    x++;
    g();
  }

  private void g() {
    System.out.println(x);
  }

  public static void main(String[] args) {
    Exercise2 e = new Exercise2();
    int x = 200;
    e.f(x);
  }
}
----
+
*연습 09.3* 다음 클래스가 _(i)_  컴파일 오류, _(ii)_  런타임 오류를
생성하는지 확인합니다. 프로그램이 오류를 생성하지 않으면 무엇을 인쇄할지
말하십시오. 프로그램에서 오류가 발생하면 오류를 수정하고 수정 후 무엇을
인쇄할지 말하세요. 답변에 동기를 부여하십시오.
+
[source,java]
----
public class Base {
  public Base() {
    infob = "I am an object of the Base class";
  }
  public String getInfo() {
    return infob;
  }
  private String infob;
}

public class Derived extends Base {
  public Derived() {
    super();
    infod = "I am an object of the Derived class";
  }
  public String getInfo() {
    return infod + ", " + super.getInfo();
  }
  private String infod;
}

public class Exercise3 {
  public static void main(String[] args) {
    Base b = new Base();
    Derived d = new Derived();
    System.out.println(b.getInfo());
    System.out.println(d.getInfo());
    b = d;
    System.out.println(b.getInfo());
  }
}
----
+
*연습 09.4* 다음 프로그램에서 모든 예외를 캡처하여 발생한 오류 유형을
설명하는 오류 메시지를 인쇄합니다.
+
[source,java]
----
import java.io.*;

public class Exercise4 {

  public static void main(String[] args) {
    int n=10;
    int[] v = new int[n];
    FileReader f = new FileReader("dati.txt");
    BufferedReader in = new BufferedReader(f);
    int i=0;
    String linea = in.readLine();
    while (linea!=null) {
      v[i] = Integer.parseInt(linea);
      linea = in.readLine();
      i++;
    }
    f.close();
  }
}
----
+
*연습 09.5* 적절한 오류 메시지를 인쇄하여 모든 예외를 명시적으로
처리하여 연습 8.6을 해결하세요.
+
*연습 09.6 "`The strings is too long`"* 라는 오류 메시지를
인쇄하는 ExceptionLineTooLong 이라는 새 예외를 정의합니다 . 파일의 모든
라인을 읽고 파일의 문자열이 80자를 초과하는
경우 ExceptionLineTooLong 유형의 예외를 발생시키는 프로그램을
작성하십시오 . 프로그램에서 발생할 수 있는 모든 예외도 처리합니다.
+
*연습 09.7* 다음 정적 메서드를 포함하는 클래스를 작성하세요:
** fileExists
+
이름이 매개 변수로 전달된 파일이 있으면 true이고, 그렇지 않으면 false인
boolean 값을 매개 변수로 사용합니다;
** isInt
+
문자열이 매개 변수 문자열이 정수를 나타내는 boolean 값을 반환합니다.
그리고 false 값을 반환합니다.
** isDouble
+
문자열을 매개 변수로 사용하고 문자열이 실수를 나타내면 true이고, 그렇지
않으면 false인 boolean 값을 반환합니다.
+
예외를 적절하게 포착하여 연습 문제를 해결하세요.
+
*연습 09.8 연습 8.9의* Matrix 클래스에서 발생할 수 있는 오류를 포착하는
데 필요한 예외를 정의합니다 .
*** ExceptionWrongMatrixValues - 파일의 데이터가 숫자 값과 일치하지
않거나 데이터가 행렬의 형태와 일치하지 않는 경우(예: 행의 길이가 서로
다름) 읽혀진 메소드로 던집니다;
*** ExceptionWrongMatrixDimension
+
파일의 데이터가 행렬의 차원과 일치하지 않을 경우 읽혀진 메서드에
던져집니다.
+
필요한 경우 새 예외를 생성하는 방식으로 Matrix 클래스를 수정합니다 .
